# Generated by Django 3.0.5 on 2021-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0002_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='listofuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_user', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
